basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: jkulvichi@gmail.com
    name: Yuri Kulagin
    url: https://t.me/jkulvich
  description: Server for api & documentation testing
  license:
    name: MIT
  termsOfService: http://swagger.io/terms
  title: GeekBrains server
  version: "1.0"
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      operationId: get-string-by-int
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show a account
swagger: "2.0"
